name: Build and Deploy

on:
  push:
    branches: [main]

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Environment
        uses: actions/setup-node@v4
        with:
          node_version: latest

      - name: Enable Corepack
        shell: bash
        run: corepack enable

      - name: Test App
        shell: bash
        run: yarn test

      - name: Deploy App
        uses: netlify/actions/build@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
          NETLIFY_CMD: yarn build
          NETLIFY_DIR: dist
