name: Build and Deploy

on:
  push:
    branches: [main]

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup environment
        uses: actions/setup-node@v4
        with:
          node_version: latest

      - name: Enable corepack
        shell: bash
        run: corepack enable

      - name: Install dependencies
        shell: bash
        run: yarn install --immutable --inline-builds

      - name: Test app
        shell: bash
        run: yarn test

      - name: Deploy app
        uses: netlify/actions/build@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
          NETLIFY_CMD: yarn build
          NETLIFY_DIR: dist
